config/routes.rb
Rails.application.routes.draw do
  root 'obras#index'

  # /obra
  resources :obras do

    # /obra/factura
    resources :facturas do
      # Filtrar facturas por situacion
      collection do
        get 'cobros'
        get 'pagos'
      end

      # /obra/factura/recibo
      # Ver los recibos de cada factura para esta obra
      # TODO acciones que sobran?
      resources :recibos, except: [ :index ]

      # /obra/factura/retención
      # Ver las retenciones de cada factura para esta obra
      resources :retenciones do
        put 'pagar'
      end
    end

    # /obra/recibo/* pero no crear recibos sin facturas asociadas
    resources :recibos, except: [ :new, :index ] do
      collection do
        get 'cobros'
        get 'pagos'
      end
    end

    # /obra/caja
    resources :cajas do

      member do
       get 'cambiar'
       get 'transferir'
      end

      # /obra/caja/cheque
      resources :cheques do
        member do
          patch 'depositar'
          patch 'cobrar'
          patch 'pagar'
        end
      end

      # /obra/caja/retencion
      resources :retenciones

    end

    # /obra/unidad_funcional
    resources :unidades_funcionales

    # /obra/retención
    resources :retenciones, only: [ :index, :show ]
    # /obra/cheque
    # no se editan cheques aca, solo se listan
    resources :cheques

    # /obra/contrato_de_venta
    resources :contratos_de_venta

    # /obra/cuotas
    resources :cuotas, only: [ :index, :show ] do
      member do
        put 'generar_factura'
      end
    end
  end

  # /caja
  resources :cajas do
    member do
      get 'cambiar'
      get 'transferir'
      patch 'operar'
    end

    # /caja/cheque
    # no se editan cheques aca, solo se listan
    resources :cheques, only: [ :index, :show, :edit ]
  end

  # /factura
  resources :facturas, except: [ :index ] do
    collection do
      # Filtrar facturas por situacion
      get 'cobros'
      get 'pagos'
    end

    # /factura/recibo - Ver los recibos de cada factura
    resources :recibos, except: [ :index ]

    # /factura/movimiento
    resources :movimientos, only: [ :new ]

    # /factura/retención - Ver las retenciones de cada factura
    resources :retenciones
  end

  # /recibo/* - No crear recibos sin facturas asociadas
  resources :recibos, except: [ :new, :index, :create ] do
    collection do
      get 'cobros'
      get 'pagos'
    end
  end

  # /tercero
  resources :terceros do
    collection do
      # Autocompletar
      get 'autocompletar_nombre' => 'terceros#autocomplete_tercero_nombre'
      get 'autocompletar_cuit' => 'terceros#autocomplete_tercero_cuit'
    end
  end

  # /indice
  resources :indices

  # /cheque
  # TODO borrar ':new' cuando ya exista interfase de carga
  resources :cheques, only: [ :index ]

  # /retención
  resources :retenciones, only: [ :index, :show ]
end

app/models/tercero.rb
# encoding: utf-8
class Tercero < ActiveRecord::Base
  # Cada tercero esta asociado a muchas facturas
  has_many :facturas, inverse_of: :tercero, dependent: :restrict_with_error
  has_many :contratos_de_venta

  # Las relaciones posibles que se pueden tener con cada tercero
  RELACIONES = %w(cliente proveedor ambos)

  # Validaciones
  validates_inclusion_of :relacion, in: RELACIONES
  validates_presence_of :nombre, :cuit
  validates_uniqueness_of :cuit
  validate :el_cuit_es_valido

  # seguramente hay una forma más elegante de hacer esto...
  def self.validar_cuit(cuit)
    # convertir a string si se pasa un número, remover los guiones si
    # era una cadena
    cuit_sin_validar = cuit.to_s.gsub /[^0-9]/, ''

    # parece que el cuit es siempre de 11 cifras
    return false unless cuit_sin_validar.length == 11

    multiplicadores = [ 5, 4, 3, 2, 7, 6, 5, 4, 3, 2, 1 ]
    resultado = 0

    # multiplica cada elemento del cuit por uno de los multiplicadores
    for i in 0..10
      resultado = resultado + cuit_sin_validar[i].to_i * multiplicadores[i]
    end

    # el cuit es valido si el resto de dividir el resultado por 11 es 0
    (resultado % 11) == 0
  end

  # Es un proveedor?
  def proveedor?
    relacion != 'cliente'
  end

  # Es un cliente?
  def cliente?
    relacion != 'proveedor'
  end

  def cuit_valido?
    Tercero.validar_cuit(cuit)
  end

  def volverse_cliente
    if proveedor?
      self.relacion = 'ambos'
    end
    relacion
  end

  private

    def el_cuit_es_valido
      errors.add(:cuit, :no_es_valido) unless cuit_valido?
    end
end

app/controllers/terceros_controller.rb
# encoding: utf-8
class TercerosController < ApplicationController
  before_action :set_tercero, only: [:show, :edit, :update, :destroy]
  before_action :set_order, only: [:index]

  autocomplete :tercero, :nombre, extra_data: [:cuit]
  autocomplete :tercero, :cuit, extra_data: [:nombre]

  def index
    @terceros = Tercero.all.order(@order)
  end

  def show
    @editar = false
  end

  def new
    @tercero = Tercero.new
    @editar = true
  end

  def edit
    @editar = true
  end

  def create
    @tercero = Tercero.new(tercero_params)

    respond_to do |format|
      if @tercero.save
        format.html { redirect_to @tercero, notice: 'Tercero creado con éxito' }
        format.json { render action: 'show', status: :created, location: @tercero }
      else
        format.html { render action: 'new' }
        format.json { render json: @tercero.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tercero.update(tercero_params)
        format.html { redirect_to @tercero, notice: 'Tercero actualizado con éxito.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tercero.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @tercero.destroy
      respond_to do |format|
        format.html { redirect_to terceros_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { render action: 'edit' }
        format.json { head :no_content }
      end
    end
  end

  private

    def set_tercero
      @tercero = Tercero.find(params[:id])
    end

    def tercero_params
      params.require(:tercero).permit(
        :nombre, :direccion, :telefono, :celular, :email, :iva, :relacion,
        :cuit, :contacto, :notas
      )
    end
end

app/helpers/terceros_helper.rb
module TercerosHelper
end

app/views/terceros/_cuit.html.erb
<%= f.fields_for :tercero do |ft| %>
  <%= ft.label :cuit, 'CUIT' %>
  <%= ft.autocomplete_field :cuit, autocompletar_cuit_terceros_path, class: 'form-control' %>
<% end %>

app/views/terceros/_form.html.erb
<%= form_for(@tercero) do |f| %>
  <% if @tercero.errors.any? %>
    <% @editar = true %>
  <% end %>
  <%= f.error_messages %>

  <fieldset <%= editar_o_bloquear %> >
    <div class="row">
      <div class="field form-group col-md-6">
        <%= f.label :nombre %><br>
        <%= f.text_field :nombre, class: 'form-control' %>
      </div>
      <div class="field form-group col-md-2">
        <%= f.label :cuit %><br>
        <%= f.text_field :cuit, class: 'form-control' %>
      </div>
      <div class="field form-group col-md-2">
        <%= f.label :iva %><br>
        <%= f.text_field :iva, class: 'form-control' %>
      </div>
      <div class="field form-group col-md-2">
        <%= f.label :relacion %><br>
        <%= f.select :relacion, Tercero::RELACIONES, { prompt: '-Elegir-' }, { class: 'form-control' } %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="field form-group">
          <%= f.label :contacto %>
          <%= f.text_field :contacto, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :email %><br>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="field form-group">
          <%= f.label :telefono %><br>
          <%= f.text_field :telefono, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :celular %><br>
          <%= f.text_field :celular, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="field form-group">
          <%= f.label :direccion %><br>
          <%= f.text_area :direccion, { class: 'form-control', rows: 4 } %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="field form-group col-md-12">
        <%= f.label :notas %><br>
        <%= f.text_area :notas, class: 'form-control' %>
      </div>
    </div>
  </fieldset>
  <br>
<% end %>

app/views/terceros/_nombre.html.erb
<%= f.hidden_field :tercero_id %>

<%= f.fields_for :tercero do |ft| %>
  <%= ft.label :nombre, 'Tercero' %>
  <%= ft.autocomplete_field :nombre, autocompletar_nombre_terceros_path, class: 'form-control' %>
<% end %>

app/views/terceros/edit.html.erb
<h2>Editar Tercero</h2>

<%= render 'form' %>

<a type="button" class="btn btn-danger col-md-2" href="<%= con_obra? tercero_path %>" data-confirm="Estas seguro?" data-method="delete" rel="nofollow">
  <span class="glyphicon glyphicon-remove-circle"></span>
  Borrar Tercero
</a>
<a type="button" class="btn btn-warning col-md-2 col-md-offset-1" href="<%= con_obra? tercero_path(@tercero) %>">
  <span class="glyphicon glyphicon-eye-open"></span>
  Ver Tercero
</a>
<a type="button" class="btn btn-success col-md-2 col-md-offset-2" id="btnGuardar">
  <span class="glyphicon glyphicon-ok"></span>
  Guardar Cambios
</a>

app/views/terceros/index.html.erb
<h2>
  Listado de Terceros
  <a type="button" class="btn btn-primary col-md-2 pull-right" href="<%= con_obra? new_tercero_path %>">
    <span class="glyphicon glyphicon-plus"></span>
    Nuevo Tercero
  </a>
</h2>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th></th>
      <th>Nombre <%= sort_links :nombre %></th>
      <th>Dirección</th>
      <th>Teléfono</th>
      <th>Celular</th>
      <th>Email</th>
      <th>Iva</th>
      <th>Relacion <%= sort_links :relacion %></th>
      <th>Cuit</th>
      <th>Facturas</th>
    </tr>
  </thead>

  <tbody>
    <% @terceros.each do |tercero| %>
      <tr class="ir-a" data-uri="<%= con_obra? tercero_path(tercero) %>">
        <td><%= link_to raw('<i class="glyphicon glyphicon-eye-open" title="Ver Tercero"></i>'), [tercero] %></td>
        <td><%= tercero.nombre %></td>
        <td><%= tercero.direccion %></td>
        <td><%= tercero.telefono %></td>
        <td><%= tercero.celular %></td>
        <td><%= tercero.email %></td>
        <td><%= tercero.iva %></td>
        <td><%= tercero.relacion %></td>
        <td><%= tercero.cuit %></td>
        <td><%= tercero.facturas.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/terceros/new.html.erb
<h2>Nuevo tercero</h2>

<%= render 'form' %>

<a type="button" class="btn btn-warning col-md-2 col-md-offset-3" href="<%= con_obra? terceros_path %>">
  <span class="glyphicon glyphicon-eye-open"></span>
   Volver al Listado
</a>
<a type="button" class="btn btn-success col-md-2 col-md-offset-2" id="btnGuardar">
  <span class="glyphicon glyphicon-ok"></span>
  Guardar Cambios
</a>

app/views/terceros/show.html.erb
<h2>Detalle de Tercero</h2>

<%= render 'form' %>

<a type="button" class="btn btn-success col-md-2" href="<%= con_obra? terceros_path %>">
  <span class="glyphicon glyphicon-eye-open"></span>
  Listar Terceros
</a>
<a type="button" class="btn btn-warning col-md-2 col-md-offset-1" href="<%= con_obra? edit_tercero_path(@tercero) %>">
  <span class="glyphicon glyphicon-edit"></span>
  Editar Tercero
</a>