config/routes.rb
Rails.application.routes.draw do
  root 'obras#index'

  # /obra
  resources :obras do

    # /obra/factura
    resources :facturas do
      # Filtrar facturas por situacion
      collection do
        get 'cobros'
        get 'pagos'
      end

      # /obra/factura/recibo
      # Ver los recibos de cada factura para esta obra
      # TODO acciones que sobran?
      resources :recibos, except: [ :index ]

      # /obra/factura/retención
      # Ver las retenciones de cada factura para esta obra
      resources :retenciones do
        put 'pagar'
      end
    end

    # /obra/recibo/* pero no crear recibos sin facturas asociadas
    resources :recibos, except: [ :new, :index ] do
      collection do
        get 'cobros'
        get 'pagos'
      end
    end

    # /obra/caja
    resources :cajas do

      member do
       get 'cambiar'
       get 'transferir'
      end

      # /obra/caja/cheque
      resources :cheques do
        member do
          patch 'depositar'
          patch 'cobrar'
          patch 'pagar'
        end
      end

      # /obra/caja/retencion
      resources :retenciones

    end

    # /obra/unidad_funcional
    resources :unidades_funcionales

    # /obra/retención
    resources :retenciones, only: [ :index, :show ]
    # /obra/cheque
    # no se editan cheques aca, solo se listan
    resources :cheques

    # /obra/contrato_de_venta
    resources :contratos_de_venta

    # /obra/cuotas
    resources :cuotas, only: [ :index, :show ] do
      member do
        put 'generar_factura'
      end
    end
  end

  # /caja
  resources :cajas do
    member do
      get 'cambiar'
      get 'transferir'
      patch 'operar'
    end

    # /caja/cheque
    # no se editan cheques aca, solo se listan
    resources :cheques, only: [ :index, :show, :edit ]
  end

  # /factura
  resources :facturas, except: [ :index ] do
    collection do
      # Filtrar facturas por situacion
      get 'cobros'
      get 'pagos'
    end

    # /factura/recibo - Ver los recibos de cada factura
    resources :recibos, except: [ :index ]

    # /factura/movimiento
    resources :movimientos, only: [ :new ]

    # /factura/retención - Ver las retenciones de cada factura
    resources :retenciones
  end

  # /recibo/* - No crear recibos sin facturas asociadas
  resources :recibos, except: [ :new, :index, :create ] do
    collection do
      get 'cobros'
      get 'pagos'
    end
  end

  # /tercero
  resources :terceros do
    collection do
      # Autocompletar
      get 'autocompletar_nombre' => 'terceros#autocomplete_tercero_nombre'
      get 'autocompletar_cuit' => 'terceros#autocomplete_tercero_cuit'
    end
  end

  # /indice
  resources :indices

  # /cheque
  # TODO borrar ':new' cuando ya exista interfase de carga
  resources :cheques, only: [ :index ]

  # /retención
  resources :retenciones, only: [ :index, :show ]
end

app/models/obra.rb
# encoding: utf-8
class Obra < ActiveRecord::Base
  has_many :cajas, dependent: :restrict_with_error
  has_many :cheques, through: :cajas
  has_many :facturas, dependent: :restrict_with_error
  has_many :recibos, -> { uniq }, through: :cajas
  has_many :retenciones, through: :facturas
  has_many :unidades_funcionales, class_name: 'UnidadFuncional'
  has_many :contratos_de_venta, class_name: 'ContratoDeVenta'
  has_many :cuotas, through: :contratos_de_venta

  # TODO mejorar esta cosa
  has_one :chequera_propia, -> { where(tipo: 'Cheques Propios') },
    class_name: 'Caja'
  has_one :chequera, -> { where(tipo: 'Cheques en Cartera') },
    class_name: 'Caja'
  has_one :caja_ganancias, -> { where(tipo: 'Retenciones de Ganancias') },
    class_name: 'Caja'
  has_one :caja_cargas_sociales, -> { where(tipo: 'Retenciones de Cargas Sociales') },
    class_name: 'Caja'

  after_create :crear_cajas

  validates_presence_of :nombre, :direccion

  # Abstracción para traer totales de facturas, se le pasa el atributo
  # que lleva el monto (importe_total, iva, importe_neto) como string,
  # la moneda y parámetros extra para filtrar.
  #
  # Luego obtiene los centavos y la moneda y devuelve un resultado
  # 
  # NOTA: no se excluyen las X
  def total_facturas(campo_monto, moneda = 'ARS', params = {})
    total = Money.new(0, moneda)
    # traer siempre siempre las facturas de la misma moneda
    params.merge!({ :"#{campo_monto}_moneda" => moneda })

    # traer solo monto_centavos, monto_moneda
    facturas.where(params).
             pluck(:"#{campo_monto}_centavos", :"#{campo_monto}_moneda").
             each do |monto|

      # todo se suma, luego se decide si mostrar los pagos como
      # negativos en la interfaz, etc.
      total += Money.new(monto[0], monto[1])

    end

    total
  end

  # calcular el total de iva
  def total_iva(params = { })
    total_facturas('iva', 'ARS', params.merge({ situacion: 'cobro' })) -
    total_facturas('iva', 'ARS', params.merge({ situacion: 'pago' }))
  end

  def saldo_de_facturas(moneda = 'ARS', params = {})
    saldo = Money.new(0, moneda)
    # filtrar todas las de la moneda especificada si o si
    facturas.where(params.merge({ importe_total_moneda: moneda })).find_each do |f|
      saldo += f.saldo
    end

    saldo
  end

  # Sumar los saldos de todas las facturas según situación
  def saldo_de(pago_o_cobro, moneda = 'ARS', params = {})
    saldo_de_facturas(moneda, params.merge({ situacion: pago_o_cobro }))
  end

  # los pagos son salidas
  def saldo_de_pago(moneda = 'ARS', params = {})
    saldo_de 'pago', moneda, params
  end

  def saldo_de_cobro(moneda = 'ARS', params = {})
    saldo_de 'cobro', moneda, params
  end

  def saldo_general(moneda = 'ARS', params = {})
    saldo_de_cobro(moneda, params) - saldo_de_pago(moneda, params)
  end

  # devuelve el total de todas las cajas para una moneda
  def total_general(moneda = 'ARS', parametros = { tipo_factura: nil })
    total = Money.new(0, moneda)
    cajas.where(parametros).find_each do |caja|
      total += caja.total(moneda)
    end

    total
  end

  private

    def crear_cajas
      ['Obra', 'Administración', 'Seguridad'].each do |tipo|
        cajas.create tipo: tipo, situacion: 'efectivo'
      end

      # Estas cajas solo aceptan factura de tipo X
      cajas.create tipo: 'Administración B', situacion: 'efectivo', tipo_factura: 'X'
      cajas.create tipo: 'Cheques en Cartera B', situacion: 'chequera', tipo_factura: 'X'

      cajas.create tipo: 'Cuenta Corriente', situacion: 'banco', banco: 'Cambiame'
      cajas.create tipo: 'Cheques en Cartera', situacion: 'chequera'
      cajas.create tipo: 'Cheques Propios', situacion: 'chequera'
      cajas.create tipo: 'Retenciones de Ganancias', situacion: 'chequera'
      cajas.create tipo: 'Retenciones de Cargas Sociales', situacion: 'chequera'
    end
end

app/controllers/obras_controller.rb
# encoding: utf-8
class ObrasController < ApplicationController
  before_action :set_obra, only: [:show, :edit, :update, :destroy]

  # GET /obras
  # GET /obras.json
  def index
    @obras = Obra.all
  end

  # GET /obras/1
  # GET /obras/1.json
  def show
    @editar = false
  end

  # GET /obras/new
  def new
    @obra = Obra.new
    @editar = true
  end

  # GET /obras/1/edit
  def edit
    @editar = true
  end

  # POST /obras
  # POST /obras.json
  def create
    @obra = Obra.new(obra_params)

    respond_to do |format|
      if @obra.save
        format.html { redirect_to @obra, notice: 'Obra creada con éxito.' }
        format.json { render action: 'show', status: :created, location: @obra }
      else
        format.html { render action: 'new' }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /obras/1
  # PATCH/PUT /obras/1.json
  def update
    respond_to do |format|
      if @obra.update(obra_params)
        format.html { redirect_to @obra, notice: 'Obra actualizada con éxito.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /obras/1
  # DELETE /obras/1.json
  def destroy
    if @obra.destroy
      respond_to do |format|
        format.html { redirect_to obras_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { render action: :edit }
        format.json { render json: @obra.errors }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_obra
      @obra = Obra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def obra_params
      params.require(:obra).permit(
        :nombre, :direccion
      )
    end
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/views/obras/_form.html.erb
<%= form_for(@obra) do |f| %>
  <% if @obra.errors.any? %>
    <% @editar = true %>
  <% end %>
  <%= f.error_messages %>

  <%# (des)habilita la edicion del formulario dependiendo del valor de @editar %>
  <fieldset <%= editar_o_bloquear %>>
    <div class="row">
      <div class="field form-group col-md-12">
        <%= f.label :nombre %><br>
        <%= f.text_field :nombre, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="field form-group col-md-12">
        <%= f.label :direccion %><br>
        <%= f.text_field :direccion, class: "form-control" %>
      </div>
    </div>
  </fieldset>

<% end %>

app/views/obras/_situacion_economica.html.erb
<div class="row col-md-12">
  <div class="row borde-abajo">
    <div class="h4 col-md-5">Situación Económica</div>
    <div class="h4 col-md-3 text-right text-bottom">en ARS &nbsp;</div>
    <div class="h4 col-md-4 text-right">en USD &nbsp;</div>
  </div>
  <div class="row borde-abajo-punteado" title="Total Facturas: suma de todas las facturas.">
    <div class="h4 col-md-4"><strong>Total Facturas</strong></div>
    <div class="h4 text-right col-md-4"><strong>
      <%= formatted_number(@obra.saldo_general('ARS')) %>
    </strong></div>
    <div class="h4 text-right col-md-4"><strong>
      <%= formatted_number(@obra.saldo_general('USD')) %>
    </strong></div>
  </div>
  <div class="row ir-a" data-uri="<%= cobros_obra_facturas_path(@obra) %>" title="Facturas por Cobrar: montos pendientes de cobro">
    <div class="col-md-4">Facturas por Cobrar</div>
    <div class="text-right col-md-4">
      <%= formatted_number(@obra.saldo_de_cobro('ARS')) %>
    </div>
    <div class="text-right col-md-4">
      <%= formatted_number(@obra.saldo_de_cobro('USD')) %>
    </div>
  </div>
  <div class="row borde-abajo ir-a" data-uri="<%= pagos_obra_facturas_path(@obra) %>" title="Facturas por Pagar: montos pendientes de pago">
    <div class="col-md-4">Facturas por Pagar</div>
    <div class="text-right col-md-4">
      <%= formatted_number(@obra.saldo_de_pago('ARS') * -1) %>
    </div>
    <div class="text-right col-md-4">
      <%= formatted_number(@obra.saldo_de_pago('USD') * -1) %>
    </div>
  </div>
  <br>
</div>

app/views/obras/_situacion_financiera.html.erb
<div class="row col-md-12">
  <div class="row borde-abajo">
    <div class="h4 col-md-5">Situación Financiera</div>
    <div class="h4 col-md-3 text-right text-bottom">en ARS &nbsp;</div>
    <div class="h4 col-md-4 text-right">en USD &nbsp;</div>
  </div>
  <div class="row borde-abajo-punteado" title="Liquidez Neta: dinero disponible no comprometido con pagos futuros">
    <div class="h4 col-md-4"><strong>Liquidez Neta</strong></div>
    <div class="h4 text-right col-md-4"><strong>
      <%= formatted_number(@obra.total_general('ARS')) %>
    </strong></div>
    <div class="h4 text-right col-md-4"><strong>
      <%= formatted_number(@obra.total_general('USD')) %>
    </strong></div>
  </div>
  <div class="row ir-a" data-uri="<%= obra_cajas_path(@obra) %>" title="Efectivo: montos disponibles en todas las cajas de la obra">
    <div class="col-md-4">Efectivo</div>
    <div class="text-right col-md-4">
      <%= formatted_number(@obra.total_general('ARS', { situacion: 'efectivo' })) %>
    </div>
    <div class="text-right col-md-4">
      <%= formatted_number(@obra.total_general('USD', { situacion: 'efectivo' })) %>
    </div>
  </div>
  <div class="row ir-a" data-uri="<%= obra_cajas_path(@obra) %>" title="Bancos: montos disponibles en todas las cuentas bancarias de la obra">
    <div class="col-md-4">Bancos</div>
    <div class="text-right col-md-4">
      <%= formatted_number(@obra.total_general('ARS', { situacion: 'banco' })) %>
    </div>
    <div class="text-right col-md-4">
      <%= formatted_number(@obra.total_general('USD', { situacion: 'banco' })) %>
    </div>
  </div>
  <div class="row ir-a" data-uri="<%= obra_cheques_path(@obra, situacion: 'terceros') %>" title="Cheques 3ros: cheques de 3ros en cartera">
    <div class="col-md-4">Cheques de 3ros</div>
    <div class="text-right col-md-4">
      <%= formatted_number(@obra.chequera.total) %>
    </div>
    <div class="text-right col-md-4">
    --- &nbsp;
    </div>
  </div>
  <div class="row ir-a" data-uri="<%= obra_cheques_path(@obra, situacion: 'propios') %>" title="Cheques Propios: cheques propios emitidos">
    <div class="col-md-4">Cheques Propios</div>
    <div class="text-right col-md-4">
      <%= formatted_number(@obra.chequera_propia.total) %>
    </div>
    <div class="text-right col-md-4">
    --- &nbsp;
    </div>
  </div>
  <div class="row borde-abajo ir-a" data-uri="<%= obra_retenciones_path(@obra, situacion: 'terceros') %>" title="Retenciones: retenciones pendientes de pago">
    <div class="col-md-4">Retenciones</div>
    <div class="text-right col-md-4">
      <%# FIXME la lógica no va en las vistas %>
      <%= formatted_number(@obra.total_general('ARS', "tipo LIKE 'Retenciones%' AND situacion = 'chequera'")) %>
    </div>
    <div class="text-right col-md-4">
      --- &nbsp;
    </div>
  </div>
  <br>
</div>

app/views/obras/edit.html.erb
<h2>Editar Obra</h2>

<div class="col-md-8">
  <div class="row">
    <%= render 'form' %>
  </div>

  <div class="row">
    <a type="button" class="btn btn-danger col-md-3" href="<%= obra_path %>" data-confirm="Estas seguro?" data-method="delete" rel="nofollow">
      <span class="glyphicon glyphicon-remove-circle"></span>
      Borrar Obra
    </a>
    <a type="button" class="btn btn-warning col-md-3 col-md-offset-1" href="<%= obra_path(@obra) %>">
      <span class="glyphicon glyphicon-eye-open"></span>
      Volver a Obra
    </a>
    <a type="button" class="btn btn-success col-md-3 col-md-offset-2" id="btnGuardar">
      <span class="glyphicon glyphicon-ok"></span>
      Guardar Cambios
    </a>
  </div>
  <div class="col-md-4">
  <%# TODO agregar informacion destacada de la obra %>
  </div>
</div>

app/views/obras/index.html.erb
<h2>Listado de Obras
  <a type="button" class="btn btn-primary col-md-2 pull-right" href="<%= new_obra_path %>">
    <span class="glyphicon glyphicon-plus"></span>
    Nueva Obra
  </a>
</h2>

<div class="row col-md-9">
  <table class="h4 table table-hover table-condensed">
    <thead>
      <tr>
        <th></th>
        <th>Nombre</th>
        <th>Direccion</th>
        <th class="text-right">Obligaciones Netas</th>
        <th class="text-right">Liquidez Neta</th>
      </tr>
    </thead>

    <tbody>
      <% @obras.each do |obra| %>
        <tr class="ir-a" data-uri="<%= obra_path(obra.id) %>">
          <td><%= link_to raw('<i class="glyphicon glyphicon-eye-open" title="Ver Obra"></i>'), [obra] %></td>
          <td><%= obra.nombre %></td>
          <td><%= obra.direccion %></td>
          <td class="text-right" data-uri='<%= obra_path(obra.id) %>'>
            <div><%= formatted_number obra.saldo_general('ARS') %> ARS</div>
            <div><%= formatted_number obra.saldo_general('USD') %> ARS</div>
          </td>
          <td class="text-right" data-uri='<%= obra_path(obra.id) %>'>
            <div><%= formatted_number obra.total_general('ARS') %> ARS</div>
            <div><%= formatted_number obra.total_general('USD') %> ARS</div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/obras/new.html.erb
<h2>Nueva Obra</h2>

<div class="col-md-8">
  <div class="row">
    <%= render 'form' %>
  </div>

  <div class="row">
    <a type="button" class="btn btn-warning col-md-3 col-md-offset-4" href="<%= obras_path %>">
      <span class="glyphicon glyphicon-eye-open"></span>
      Volver al Listado
    </a>
    <a type="button" class="btn btn-success col-md-3 col-md-offset-2" id="btnGuardar">
      <span class="glyphicon glyphicon-ok"></span>
      Guardar Cambios
    </a>
  </div>
</div>

app/views/obras/show.html.erb
<h2><%= @obra.nombre %></h2> 

<div class="row">
  <div class="col-md-6">

    <%= render 'situacion_economica' %>

    <div class="row col-md-12">
      <%= render 'form' %>
      <br>

      <a type="button" class="btn btn-success col-md-5" href="<%= obras_path %>">
        <span class="glyphicon glyphicon-list-alt"></span>
        Listar Obras
      </a>
      <a type="button" class="btn btn-warning col-md-5 col-md-offset-2" href="<%= edit_obra_path(@obra) %>">
        <span class="glyphicon glyphicon-edit"></span>
        Editar Obra
      </a>
    </div>
  </div>

  <div class="col-md-6">
    <%= render 'situacion_financiera' %>
    <%= render 'unidades_funcionales/reporte' %>

  </div>
</div>