config/routes.rb
Rails.application.routes.draw do
  root 'obras#index'

  # /obra
  resources :obras do

    # /obra/factura
    resources :facturas do
      # Filtrar facturas por situacion
      collection do
        get 'cobros'
        get 'pagos'
      end

      # /obra/factura/recibo
      # Ver los recibos de cada factura para esta obra
      # TODO acciones que sobran?
      resources :recibos, except: [ :index ]

      # /obra/factura/retención
      # Ver las retenciones de cada factura para esta obra
      resources :retenciones do
        put 'pagar'
      end
    end

    # /obra/recibo/* pero no crear recibos sin facturas asociadas
    resources :recibos, except: [ :new, :index ] do
      collection do
        get 'cobros'
        get 'pagos'
      end
    end

    # /obra/caja
    resources :cajas do

      member do
       get 'cambiar'
       get 'transferir'
      end

      # /obra/caja/cheque
      resources :cheques do
        member do
          patch 'depositar'
          patch 'cobrar'
          patch 'pagar'
        end
      end

      # /obra/caja/retencion
      resources :retenciones

    end

    # /obra/unidad_funcional
    resources :unidades_funcionales

    # /obra/retención
    resources :retenciones, only: [ :index, :show ]
    # /obra/cheque
    # no se editan cheques aca, solo se listan
    resources :cheques

    # /obra/contrato_de_venta
    resources :contratos_de_venta

    # /obra/cuotas
    resources :cuotas, only: [ :index, :show ] do
      member do
        put 'generar_factura'
      end
    end
  end

  # /caja
  resources :cajas do
    member do
      get 'cambiar'
      get 'transferir'
      patch 'operar'
    end

    # /caja/cheque
    # no se editan cheques aca, solo se listan
    resources :cheques, only: [ :index, :show, :edit ]
  end

  # /factura
  resources :facturas, except: [ :index ] do
    collection do
      # Filtrar facturas por situacion
      get 'cobros'
      get 'pagos'
    end

    # /factura/recibo - Ver los recibos de cada factura
    resources :recibos, except: [ :index ]

    # /factura/movimiento
    resources :movimientos, only: [ :new ]

    # /factura/retención - Ver las retenciones de cada factura
    resources :retenciones
  end

  # /recibo/* - No crear recibos sin facturas asociadas
  resources :recibos, except: [ :new, :index, :create ] do
    collection do
      get 'cobros'
      get 'pagos'
    end
  end

  # /tercero
  resources :terceros do
    collection do
      # Autocompletar
      get 'autocompletar_nombre' => 'terceros#autocomplete_tercero_nombre'
      get 'autocompletar_cuit' => 'terceros#autocomplete_tercero_cuit'
    end
  end

  # /indice
  resources :indices

  # /cheque
  # TODO borrar ':new' cuando ya exista interfase de carga
  resources :cheques, only: [ :index ]

  # /retención
  resources :retenciones, only: [ :index, :show ]
end

app/models/cheque.rb
# encoding: utf-8
# Los cheques son promesas de cobro o pago, es decir que son movimientos
# futuros
# Solo se pueden depositar cuando están vencidos
# Solo cuando se depositan generan un movimiento (positivo o negativo)
# en el recibo al que pertenecen
class Cheque < ActiveRecord::Base
  include CausaDeMovimientos

  class ErrorEnUsarParaPagar < ActiveRecord::ActiveRecordError; end;

  # Los cheques tienen una cuenta sólo si son propios o han sido depositados
  belongs_to :cuenta, -> { where(situacion: 'banco') },
    class_name: 'Caja'
  belongs_to :chequera, -> { where(situacion: 'chequera') },
    class_name: 'Caja'

  has_one :obra, through: :chequera

  has_many :recibos, through: :movimientos do
    # TODO hay casos donde haya más de un recibo interno?
    def interno
      where(situacion: 'interno').first
    end
  end

  SITUACIONES = %w(propio terceros)
  validates_inclusion_of :situacion, in: SITUACIONES

  ESTADOS = %w(chequera depositado cobrado rechazado pagado pasamanos)
  validates_inclusion_of :estado, in: ESTADOS

  # campos requeridos
  validates_presence_of :fecha_emision, :fecha_vencimiento, :monto,
                        :banco

  # Todos los cheques pertenecen a una chequera, si son de terceros es donde se
  # contabiliza el pago, si son propios es de donde se contabiliza la emisión
  # del cheque
  validates_presence_of :chequera
  validate :tipo_de_chequera, :tipo_de_cuenta
  validates_numericality_of :monto_centavos, greater_than: 0

  monetize :monto_centavos, with_model_currency: :monto_moneda

  before_validation :adoptar_banco_de_cuenta

  scope :depositados, -> { where(estado: 'depositado') }
  scope :de_terceros, -> { where(situacion: 'terceros') }
  scope :propios, -> { where(situacion: 'propio') }

  # Trae todos los cheques vencidos, si se le pasa una fecha trae los
  # vencidos a ese momento
  # TODO testear
  def self.vencidos(time = nil)
    where('fecha_vencimiento < ?', time || Time.now)
  end

  def self.construir(params)
    cheque_de_terceros_id = params.extract! :cheque_id

    parametros_permitidos = params.permit :cuenta_id, :chequera_id, :monto,
      :monto_moneda, :numero, :fecha_emision, :beneficiario,
      :fecha_vencimiento, :situacion, :banco

    # TODO scopear a obra y cosas así
    if cheque_de_terceros_id.present?
      find(cheque_de_terceros_id[:cheque_id])
    else
      new parametros_permitidos
    end
  end

  # Es una causa de movimientos de la cuál nos interesa preservar información
  def trackeable?
    true
  end

  def vencido?
    fecha_vencimiento < Time.now
  end

  def propio?
    situacion == 'propio'
  end

  def terceros?
    situacion == 'terceros'
  end

  def depositado?
    estado == 'depositado'
  end

  def pagado?
    estado == 'pagado'
  end

  def chequera?
    estado == 'chequera'
  end

  def pasamanos?
    estado == 'pasamanos'
  end

  # Para poder cobrar un cheque de terceros, antes se deposita en una
  # caja y se espera que el banco lo verifique.
  def depositar(cuenta_destino)
    # TODO validar
    # solo los cheques de terceros se depositan
    return nil unless terceros?
    # no se pueden depositar cheques en chequeras
    return nil if cuenta_destino.chequera?

    # El cheque se saca de una caja y se deposita en otra, como todavía
    # no lo cobramos, solo se indica que se depositará el dinero en una
    # caja
    update(estado: 'depositado', cuenta: cuenta_destino)

    self
  end

  # Cuando se cobra un cheque depositado, se termina una transferencia de
  # la chequera a la caja destino
  def cobrar
    # solo los cheques depositados se pueden cobrar
    return nil unless depositado?

    Cheque.transaction do
      # terminar de transferir el monto del cheque de la chequera a la
      # caja destino
      chequera.transferir(monto, cuenta)

      # marcar el cheque como cobrado
      update(estado: 'cobrado')
    end

    self
  end

  # Los cheques extraen de su cuenta y saldan la chequera cuando
  # se pagan, sólo pueden ser cheques propios
  # TODO verificar esto ↑
  def pagar
    # Los cheques pagados no se pueden pagar dos veces!
    return nil if pagado?
    # solo los cheques de terceros que se pasaron de manos se pueden
    # pagar
    return nil if terceros?

    Cheque.transaction do
      self.estado = 'pagado'
      recibo = Recibo.interno_nuevo
      salida = cuenta.extraer(monto, true)
      salida.causa = self

      entrada = chequera.depositar(monto, true)
      entrada.causa = self

      recibo.movimientos << salida << entrada

      save
    end

    rescue ActiveRecord::ActiveRecordError => excepcion
      self.errors.add(:base, excepcion.message)
      false
  end

  # Usar este cheque como medio de pago. Lo asociamos como causa del movimiento
  # de extracción de su caja, y asociamos el recibo de pago al movimiento.
  def usar_para_pagar(este_recibo)
    # tienen que estar en la chequera
    raise ErrorEnUsarParaPagar, I18n.t('cheques.error_en_usar_para_pagar') unless chequera?
    # y se asocian a recibos de pago
    raise ErrorEnUsarParaPagar, I18n.t('cheques.error_en_usar_para_pagar') unless este_recibo.pago?

    Cheque.transaction do
      # TODO Qué estado ponerle a un cheque propio usado como pago?
      self.estado = 'pasamanos' if terceros?
      movimiento = chequera.extraer(monto, true)
      # si no salvamos aca, al movimiento le va a llegar como causa un
      # cheque no existe y falla todo
      save
      movimiento.causa = self
      movimiento.recibo = este_recibo
      movimiento
    end
  end

  # TODO pasar un concern
  def usar_para_cobrar(este_recibo)
    if terceros?
      Cheque.transaction do
        if movimiento = chequera.depositar(monto, true)
          save
          movimiento.causa = self
          movimiento.recibo = este_recibo
          movimiento
        else
          false
        end
      end
    else
      errors.add(:situacion, :debe_ser_de_terceros)
      false
    end
  end

  def descripcion
    "#{monto_moneda} #{monto} - #{beneficiario} (vence el #{I18n.l fecha_vencimiento.to_date})"
  end

  private

    def tipo_de_chequera
      errors.add(:chequera_id, :debe_ser_una_chequera) unless chequera.chequera?
    end

    def tipo_de_cuenta
      if cuenta.present?
        errors.add(:cuenta_id, :debe_ser_una_cuenta_de_banco) unless cuenta.banco?
      end
    end

    def adoptar_banco_de_cuenta
      if propio?
        self.banco = cuenta.try :banco
      end
    end
end

app/models/cheques.rb
class Cheque < ActiveRecord::Base
  belongs_to :cuenta

  SITUACIONES = %w(propio terceros)
  validates_inclusion_of :situacion, in: SITUACIONES
  validates_presence_of :fecha_vencimiento, :monto

  monetize :monto_centavos

  def vencido?
    fecha_vencimiento > Time.now
  end

  def propio?
    situacion == 'propio'
  end

  def terceros?
    situacion == 'terceros'
  end
end

app/controllers/cheques_controller.rb
# encoding: utf-8
class ChequesController < ApplicationController
  before_action :set_obra
  before_action :set_caja
  before_action :set_cheques, only: [ :index ]
  before_action :set_cheque, only: [ :show, :edit, :update, :destroy, :depositar, :pagar, :cobrar ]
  before_action :set_order, only: [ :index ]
  before_action :set_recibos, only: [ :show ]

  def index
    @situacion = params[:situacion]
    @cheques = @cheques.where(situacion: params[:situacion]) if params[:situacion]
    @cheques = @cheques.where(estado: params[:estado]) if params[:estado]
    @cheques = @cheques.vencidos if params[:vencidos]
    @cheques = @cheques.depositados if params[:depositados]

    @cheques = @cheques.order(@order)
  end

  def show
    @editar = false
  end

  # TODO borrar 'new' cuando exista interfase para crear cheques
  def new
    @cheque = Cheque.new
    @editar = true
  end

  def edit
    @editar = true
  end

  def create
    @cheque = Cheque.new(cheque_params)

    respond_to do |format|
      if @cheque.save
        format.html do
          redirect_to [@cheque.chequera.obra, @cheque.chequera, @cheque],
            notice: 'Cheque creado con éxito.'
        end
        format.json do
          render action: 'show', status: :created,
            location: [@cheque.chequera.obra, @cheque.chequera, @cheque]
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @cheque.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cheque.update(cheque_params)
        format.html do
          redirect_to [@cheque.chequera.obra, @cheque.chequera, @cheque],
            notice: 'Cheque actualizado con éxito.'
        end
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cheque.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    volver_a_listado = obra_cajas_url @cheque.chequera.obra, @cheque.chequera
    @cheque.destroy
    respond_to do |format|
      format.html { redirect_to volver_a_listado }
      format.json { head :no_content }
    end
  end

  def pagar
    @cheque = Cheque.find(params[:id])
    respond_to do |format|

      if @cheque.pagar
        format.html do
          redirect_to obra_cheques_path(@cheque.chequera.obra, situacion: 'propio'),
            notice: 'Cheque pagado con éxito'
        end
        format.json { head :no_content }
      else
        format.html { render action: 'show' }
        format.json { render json: @cheque.errors, status: :unprocessable_entity }
      end
    end
  end

  def depositar
    respond_to do |format|
      if @cheque.depositar(Caja.find(params[:cheque][:cuenta_id]))
        format.html do
          redirect_to [@cheque.chequera.obra,@cheque.chequera,@cheque],
            notice: 'Cheque depositado con éxito'
        end
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cheque.errors, status: :unprocessable_entity }
      end
    end
  end

  def cobrar
    @cheque = Cheque.find(params[:id])
    respond_to do |format|
      if @cheque.cobrar
        format.html do
          redirect_to [@cheque.chequera.obra,@cheque.chequera,@cheque],
            notice: 'Cheque cobrado con éxito'
        end
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cheque.errors, status: :unprocessable_entity }
      end
    end
  end


  private

    def set_cheque
      @cheque = (@obra.present? ? @obra.cheques : Cheque).find(params[:id])
    end

    def set_cheques
      @cheques = if @caja.present?
        @caja.cheques
      elseif @obra.present?
        @obra.cheques
      else
        Cheque.all
      end
    end

    def cheque_params
      params.require(:cheque).permit(
        :situacion, :numero, :monto, :monto_centavos, :monto_moneda,
        :fecha_vencimiento, :fecha_emision, :beneficiario, :banco, :estado,
        :chequera_id, :cuenta_id, :obra_id
      )
    end

    def set_caja
      if params[:caja_id]
        @caja = (@obra.present? ? @obra.cajas : Caja).find(params[:caja_id])
      end
    end

    def set_recibos
      @recibos = @cheque.recibos.uniq
    end
end

app/helpers/cheques_helper.rb
module ChequesHelper
  def titulo_vista_cheque
    @cheque.propio? ? 'Detalles de Cheque Propio' : 'Detalles de Cheque de Tercero'
  end

  def titulo_listado_cheques
    titulo = 'Listado de Cheques'
    case params[:situacion]
      when 'propio' then titulo += ' Propios'
      when 'terceros' then titulo += ' de Terceros'
    end

    titulo += ' depositados' if params[:depositados]
    # TODO cambiar a fecha seleccionada
    titulo += " vencidos al #{formatted_date(Time.now)}" if params[:vencidos]

    titulo
  end

  def path_a_listado
    @cheque.propio? ? propios_cheques_path : terceros_cheques_path
  end

  def actualiza_situacion
    params[:situacion] ? @cheque.situacion = params[:situacion] : ''
  end

  def etiqueta_de_estado(estado)
    case estado
      when 'chequera' then 'label-primary'
      when 'depositado' then 'label-info'
      when 'cobrado' then 'label-success'
      when 'rechazado' then 'label-warning'
      when 'pagado' then 'label-primary'
      when 'pasamanos' then 'label-warning'
      else 'label-default'
    end
  end
end

app/views/cheques/_cobrar.html.erb
<%= form_for [cheque.chequera.obra, cheque.chequera, cheque],
             html: { class: 'pull-right' },
             url: cobrar_obra_caja_cheque_url(cheque.chequera.obra, cheque.chequera, cheque),
             method: :patch do |f| %>
  <%= f.submit class: 'btn btn-sm btn-success', value: 'Cobrar' %>
<% end %>

app/views/cheques/_depositar.html.erb
<%= form_for [cheque.chequera.obra, cheque.chequera, cheque],
             html: { class: 'form-inline pull-right' },
             url: depositar_obra_caja_cheque_url(cheque.chequera.obra, cheque.chequera, cheque),
             method: :patch do |f| %>
  <%= f.collection_select(:cuenta_id,
        cheque.chequera.obra.cajas.where(situacion: 'banco'),
        :id,
        :tipo, { prompt: '-Seleccione Caja-' },
        { class: 'form-control input-sm' } ) %>
  <%= f.submit class: 'btn btn-sm btn-info', value: 'Depositar' %>
<% end %>

app/views/cheques/_form.html.erb
<%= form_for([@obra, @caja, @cheque]) do |f| %>
  <% if @cheque.errors.any? %>
    <% @editar = true %>
  <% end %>
  <%= f.error_messages %>

  <fieldset <%= editar_o_bloquear %>>

    <div class="row">
      <div class="field form-group col-md-4">
        <%# Solo se puede modificar la cuenta cuando el cheque fue emitido o depositado, no cuando ya se cobró o pagó%>
        <%= f.label :cuenta %>
        <% if (@cheque.propio? && @cheque.chequera?) || (@cheque.terceros? && @cheque.depositado?) %>
          <%= f.collection_select :cuenta_id, @cheque.chequera.obra.cajas.cuentas, :id, :banco_tipo_numero,
              { prompt: '-Seleccione Cuenta-' }, { class: 'form-control', required: true } %>
        <% elsif @cheque.cuenta.present? %>
          <p><%= @cheque.cuenta.banco_tipo_numero %></p>
        <% else %>
          <p>No está asociado a ninguna cuenta.</p>
        <% end %>

        <label>Chequera</label>
        <p><%= @cheque.chequera.banco_tipo_numero %></p>
      </div>

      <div class="field form-group col-md-3 col-md-offset-2">
        <%= f.label :fecha_emision %><br>
        <div class="input-group date">
          <%= f.text_field :fecha_emision, class: 'form-control',
              value: formatted_date(@cheque.fecha_emision) %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
        </div>
      </div>

      <div class="field form-group col-md-3">
        <%= f.label :fecha_vencimiento %><br>
        <div class="input-group date">
          <%= f.text_field :fecha_vencimiento, class: 'form-control',
              value: formatted_date(@cheque.fecha_vencimiento) %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
        </div>
      </div>

    </div>

    <div class="row">
      <div class="field form-group col-md-6">
        <%= f.label :beneficiario %><br>
        <%= f.text_field :beneficiario, class: 'form-control' %>
      </div>
      <div class="field form-group col-md-2 col-md-offset-1">
        <label class='text-right'>Moneda</label><br>
        <span class='form-control text-right'>ARS</span>
      </div>
      <div class="field form-group col-md-3">
        <%= f.label :monto, class: 'text-right'%><br>
        <%= f.text_field :monto, { class: 'form-control text-right', data: {role: 'money', a_sep:'.', a_dec:',' } } %>
      </div>
    </div>

    <div class="row">
      <div class="field form-group col-md-3">
        <%= f.label :banco %><br>
        <%= f.text_field :banco, class: 'form-control', placeholder: 'Según la caja' %>
      </div>

      <div class="field form-group col-md-3">
        <%= f.label :numero %><br>
        <%= f.text_field :numero, class: 'form-control' %>
      </div>
    </div>

    <div class="row">
      <br>
    </div>

    <%# campo necesario para crear/editar cheques %>
    <%= f.hidden_field :estado %>
    <% actualiza_situacion %>
    <%= f.hidden_field :situacion %>

  </fieldset>

<% end %>

app/views/cheques/_list.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th></th>
      <th>Situación</th>
      <th>Estado</th>
      <th>Emisión</th>
      <th>Vencimiento <%= sort_links :fecha_vencimiento %></th>
      <th>Monto <%= sort_links :monto_centavos %></th>
      <th>Beneficiario</th>
      <th>Chequera</th>
      <th>Banco</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cheques.each do |cheque| %>
      <tr class="ir-a" data-uri="<%= obra_caja_cheque_path(cheque.chequera.obra, cheque.chequera, cheque.id) %>">
        <td><%= link_to '', [cheque.chequera.obra, cheque.chequera, cheque], class:'glyphicon glyphicon-eye-open' %></td>
        <td class="h4 text-center"><span class="label <%= etiqueta_de_situacion cheque.situacion %>"><%= cheque.situacion %></span></td>
        <td class="h4 text-center"><span class="label <%= etiqueta_de_estado cheque.estado %>"><%= cheque.estado %></span></td>
        <td><%= formatted_date(cheque.fecha_emision) %></td>
        <td><%= formatted_date(cheque.fecha_vencimiento) %></td>
        <td><%= formatted_number(cheque.monto, cheque.monto_moneda) %></td>
        <td><%= cheque.beneficiario %></td>
        <td><%= cheque.chequera.tipo %></td>
        <td><%= cheque.banco %></td>
        <td>
          <% if cheque.terceros? and cheque.chequera? %>
          <%= render 'cheques/depositar', cheque: cheque %>
          <% elsif cheque.depositado? %>
          <%= render 'cheques/cobrar', cheque: cheque %>
          <% elsif cheque.propio? and cheque.chequera? %>
          <%= render 'cheques/pagar', cheque: cheque %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cheques/_pagar.html.erb
<%= form_for [cheque.chequera.obra, cheque.chequera, cheque],
             html: { class: 'pull-right' },
             url: pagar_obra_caja_cheque_url(cheque.chequera.obra, cheque.chequera, cheque),
             method: :patch do |f| %>
  <%= f.submit class: 'btn btn-sm btn-warning', value: 'Pagar' %>
<% end %>

app/views/cheques/edit.html.erb
<h2>Editar Cheque
    <span class="label <%= etiqueta_de_estado @cheque.estado %>"><%= @cheque.estado %></span>
</h2>
<div class="col-md-8">
  <div class="row">
    <%= render 'form' %>
  </div>

  <div class="row">
    <a type="button" class="btn btn-danger col-md-3" href="<%= obra_caja_cheque_path(@obra, @cheque.chequera, @cheque) %>" data-confirm="Estas seguro?" data-method="delete" rel="nofollow">
      <span class="glyphicon glyphicon-remove-circle"></span>
      Borrar Cheque
    </a>
    <a type="button" class="btn btn-warning col-md-3 col-md-offset-1" href="<%= obra_caja_cheque_path(@obra, @cheque.chequera, @cheque) %>">
      <span class="glyphicon glyphicon-eye-open"></span>
      Volver a Cheque
    </a>
    <a type="button" class="btn btn-success col-md-3 col-md-offset-2" id="btnGuardar">
      <span class="glyphicon glyphicon-ok"></span>
      Guardar Cambios
    </a>
  </div>
</div>

app/views/cheques/index.html.erb
<h2><%= titulo_listado_cheques %>
  <%# TODO poner un selector de fecha aca %>
</h2>
<div class="pull-right h4">
  <a class="label label-success" href="<%= con_obra? cheques_path(situacion: @situacion) %>">todos</a>
  <a class="label label-primary" href="<%= con_obra? cheques_path(situacion: @situacion, estado: :chequera) %>">chequera</a>
<% if @situacion == 'propio' %>
  <a class="label label-primary" href="<%= con_obra? cheques_path(situacion: 'propio', estado: :pagado) %>">pagado</a>
<% end %>

<% if @situacion == 'terceros' %>
  <a class="label label-primary" href="<%= con_obra? cheques_path(situacion: 'terceros', estado: :pasamanos) %>">pasamanos</a>
  <a class="label label-primary" href="<%= con_obra? cheques_path(situacion: 'terceros', estado: [:depositado, :cobrado]) %>">depositados/cobrados</a>
  <a class="label label-primary" href="<%= con_obra? cheques_path(situacion: 'terceros', estado: :rechazado) %>">rechazados</a>
<% end %>
</div>
<%= render 'list' %>

app/views/cheques/show.html.erb
<h2><%= titulo_vista_cheque %>
    <span class="label <%= etiqueta_de_estado @cheque.estado %>"><%= @cheque.estado %></span>
</h2>
<div class="col-md-8">
  <div class="row">
    <%= render 'form' %>
  </div>

  <div class="row">
    <a type="button" class="btn btn-success col-md-3" href="<%= obra_caja_path(@obra, @cheque.chequera) %>">
      <span class="glyphicon glyphicon-list-alt"></span>
      Ver chequera
    </a>
    <a type="button" class="btn btn-warning col-md-3 col-md-offset-1" href="<%= edit_obra_caja_cheque_path(@obra, @cheque.chequera, @cheque) %>">
      <span class="glyphicon glyphicon-edit"></span>
      Editar Cheque
    </a>
  </div>
</div>

<div class="col-md-4">
  <h4>Recibos</h4>
  <%= render 'recibos/list', recibos: @cheque.recibos %>
</div>