config/routes.rb
Rails.application.routes.draw do
  root 'obras#index'

  # /obra
  resources :obras do

    # /obra/factura
    resources :facturas do
      # Filtrar facturas por situacion
      collection do
        get 'cobros'
        get 'pagos'
      end

      # /obra/factura/recibo
      # Ver los recibos de cada factura para esta obra
      # TODO acciones que sobran?
      resources :recibos, except: [ :index ]

      # /obra/factura/retención
      # Ver las retenciones de cada factura para esta obra
      resources :retenciones do
        put 'pagar'
      end
    end

    # /obra/recibo/* pero no crear recibos sin facturas asociadas
    resources :recibos, except: [ :new, :index ] do
      collection do
        get 'cobros'
        get 'pagos'
      end
    end

    # /obra/caja
    resources :cajas do

      member do
       get 'cambiar'
       get 'transferir'
      end

      # /obra/caja/cheque
      resources :cheques do
        member do
          patch 'depositar'
          patch 'cobrar'
          patch 'pagar'
        end
      end

      # /obra/caja/retencion
      resources :retenciones

    end

    # /obra/unidad_funcional
    resources :unidades_funcionales

    # /obra/retención
    resources :retenciones, only: [ :index, :show ]
    # /obra/cheque
    # no se editan cheques aca, solo se listan
    resources :cheques

    # /obra/contrato_de_venta
    resources :contratos_de_venta

    # /obra/cuotas
    resources :cuotas, only: [ :index, :show ] do
      member do
        put 'generar_factura'
      end
    end
  end

  # /caja
  resources :cajas do
    member do
      get 'cambiar'
      get 'transferir'
      patch 'operar'
    end

    # /caja/cheque
    # no se editan cheques aca, solo se listan
    resources :cheques, only: [ :index, :show, :edit ]
  end

  # /factura
  resources :facturas, except: [ :index ] do
    collection do
      # Filtrar facturas por situacion
      get 'cobros'
      get 'pagos'
    end

    # /factura/recibo - Ver los recibos de cada factura
    resources :recibos, except: [ :index ]

    # /factura/movimiento
    resources :movimientos, only: [ :new ]

    # /factura/retención - Ver las retenciones de cada factura
    resources :retenciones
  end

  # /recibo/* - No crear recibos sin facturas asociadas
  resources :recibos, except: [ :new, :index, :create ] do
    collection do
      get 'cobros'
      get 'pagos'
    end
  end

  # /tercero
  resources :terceros do
    collection do
      # Autocompletar
      get 'autocompletar_nombre' => 'terceros#autocomplete_tercero_nombre'
      get 'autocompletar_cuit' => 'terceros#autocomplete_tercero_cuit'
    end
  end

  # /indice
  resources :indices

  # /cheque
  # TODO borrar ':new' cuando ya exista interfase de carga
  resources :cheques, only: [ :index ]

  # /retención
  resources :retenciones, only: [ :index, :show ]
end

app/models/caja.rb
# encoding: utf-8
class Caja < ActiveRecord::Base
  class ErrorEnDeposito < ActiveRecord::ActiveRecordError; end;
  class ErrorEnExtraccion < ActiveRecord::ActiveRecordError; end;

  default_scope { where(archivada: false) }

  belongs_to :obra, inverse_of: :cajas
  has_many :movimientos
  has_many :cheques, foreign_key: 'chequera_id'
  has_many :cheques_en_cuenta, foreign_key: 'cuenta_id', class_name: 'Cheque'
  has_many :retenciones, foreign_key: 'chequera_id'
  has_many :retenciones_a_pagar, foreign_key: 'cuenta_id', class_name: 'Retencion'
  has_many :recibos, through: :movimientos

  validates_presence_of :obra_id, :tipo
  validates_uniqueness_of :tipo, scope: [:obra_id, :numero]
  validates_presence_of :banco, if: :cuenta?

  # Las cajas son de efectivo, bancarias o chequeras
  SITUACIONES = %w(efectivo banco chequera)
  validates_inclusion_of :situacion, in: SITUACIONES

  # Garantiza que los nuevos tipos escritos parecido a los viejos se corrijan
  # con los valores viejos
  normalize_attribute :tipo, with: [ :squish, :blank ] do |valor|
    tipos_normalizados = tipos.inject({}) do |hash_de_tipos, tipo|
      hash_de_tipos[tipo.parameterize] = tipo and hash_de_tipos
    end

    if valor.present?
      if tipos_normalizados.keys.include?(valor.parameterize)
        tipos_normalizados[valor.parameterize]
      else
        valor
      end
    end
  end

  scope :cuentas, -> { where(situacion: 'banco') }
  scope :chequeras, -> { where(situacion: 'chequera') }
  scope :de_efectivo, -> { where(situacion: 'efectivo') }

  def self.con_fondos_en(moneda)
    joins(:movimientos).where('movimientos.monto_moneda = ?', moneda)
  end

  def banco?
    situacion == 'banco'
  end
  alias_method :cuenta?, :banco?

  def efectivo?
    situacion == 'efectivo'
  end

  def chequera?
    situacion == 'chequera'
  end

  def self.tipos
    pluck(:tipo).uniq
  end

  # Traer todas las monedas usadas
  def monedas
    movimientos.pluck(:monto_moneda).uniq
  end

  def banco_tipo_numero
    "#{banco}  - #{tipo} - ...#{(numero || 'S/N').last(4)}"
  end

  # TODO ver si hace falta un caso especial con movimientos sin guardar
  def total(moneda = 'ARS')
    Money.new(movimientos.where(monto_moneda: moneda).sum(:monto_centavos), moneda)
  end

  def totales
    if movimientos.empty?
      { 'ARS' => Money.new(0) }
    else
      movimientos.pluck(:monto_moneda).uniq.inject({}) do |hash, moneda|
        hash[moneda] = total(moneda)
        hash
      end
    end
  end

  # Te doy 3 pesos por tus 100 dólares
  def cambiar(cantidad, cantidad_aceptada)
    Caja.transaction do
      recibo = Recibo.interno_nuevo
      salida = extraer(cantidad, true)
      entrada = depositar(cantidad_aceptada, true)
      salida.causa = entrada.causa = Operacion.new
      recibo.movimientos << salida << entrada
      recibo
    end
  end

  # transferir un monto de una caja a otra
  def transferir(monto, caja)
    Caja.transaction do
      recibo = Recibo.interno_nuevo
      salida = extraer(monto, true)
      entrada = caja.depositar(monto, true)
      salida.causa = entrada.causa = Operacion.new
      recibo.movimientos << salida << entrada
      recibo
    end
  end

  # Sólo si se extrae de una cuenta, una chequera, o una caja con suficiente saldo,
  # devolvemos el movimiento realizado, caso contrario no devolvemos nada,
  # opcionalmente una excepción para frenar la transacción
  def extraer(cantidad, lanzar_excepcion = false)
    if cantidad.positive? &&
      (cantidad <= total(cantidad.currency.iso_code) || chequera? || cuenta?)
      depositar(cantidad * -1, false)
    else
      raise ErrorEnExtraccion, I18n.t('cajas.error_en_extraccion') if lanzar_excepcion
      invalido = movimientos.build monto: Money.new(0)
      invalido.errors.add(:monto, :no_hay_fondos_suficientes)
      invalido
    end
  end

  # Carga una extracción en esta caja respaldada con un recibo interno
  def extraer!(cantidad)
    Caja.transaction do
      recibo = Recibo.interno_nuevo
      salida = extraer(cantidad, true)
      salida.causa = Operacion.new
      recibo.movimientos << salida
      recibo
    end
  end

  # Devolvemos el movimiento realizado, u opcionalmente una excepción para
  # frenar la transacción.
  #
  # Si el tipo de caja es banco, esto se considera una transferencia
  # bancaria
  def depositar(cantidad, lanzar_excepcion = false)
    if movimiento = movimientos.build(monto: cantidad)
      movimiento
    else
      raise ErrorEnDeposito, I18n.t('cajas.error_en_deposito') if lanzar_excepcion
    end
  end

  # Carga un depósito en esta caja respaldado con un recibo interno
  def depositar!(cantidad)
    Caja.transaction do
      recibo = Recibo.interno_nuevo
      entrada = depositar(cantidad, true)
      entrada.causa = Operacion.new
      recibo.movimientos << entrada
      recibo
    end
  end

  # TODO revisar necesidad
  def depositar_cheque(cheque)
    cheque.depositar self
  end

  # TODO revisar necesidad
  def cobrar_cheque(cheque)
    cheque.cobrar
  end

  # Devuelve un cheque nuevo que puede usarse para pagar algún recibo.
  # Recién cuando se usa se extrae el monto de la chequera. Recién cuando se
  # paga se extrae el monto de la cuenta y se salda la chequera
  # TODO validar que self sea una cuenta
  # TODO validar parametros?
  def emitir_cheque(parametros = {})
    # Siempre emitimos desde la chequera de la obra
    parametros.merge!(chequera: obra.chequera_propia)
    # y cuando corresponda sacaremos el monto de esta cuenta
    cheques_en_cuenta.propios.create parametros
  end

  # TODO revisar necesidad. puede ser que complete el ciclo de movimientos pero
  # mejor haría un 'pagar_todo'
  def pagar_cheque(cheque)
    cheque.pagar
  end

  # las cajas no se pueden destruir, solo se marcan como archivadas 
  def archivar
    totales.each do |total|
      if total[1] > 0
        errors.add :base, :no_archivar_con_saldo
        return nil
      end
    end

    self.archivada = true
    save
  end

  def descripcion
    "#{efectivo? ? 'Caja' : banco} - #{tipo}"
  end

  # se fija si acepta facturas validas o no
  def factura_valida?
    Cp::Application.config.tipos_validos.include? tipo_factura
  end

  def factura_invalida?
    not factura_valida?
  end
end

app/controllers/cajas_controller.rb
# encoding: utf-8
class CajasController < ApplicationController
  before_action :set_obra
  before_action :set_caja, except: [ :index, :new, :create ]
  before_action :set_order, only: [ :show ]

  def index
    @cajas =     (@obra ? @obra.cajas : Caja).de_efectivo.order(:tipo)
    @cuentas =   (@obra ? @obra.cajas : Caja).cuentas.order(:tipo)
    @chequeras = (@obra ? @obra.cajas : Caja).chequeras.order(:tipo)
  end

  def show
    @editar = false

    if @caja.chequera?
      @cheques = @caja.cheques
      # TODO filtrar usando la barrita de filtro del listado de cheques
      @cheques = @cheques.order(@order)
    end
  end

  def new
    @caja = Caja.new obra: @obra
    @editar = true
  end

  def edit
    @editar = true
  end

  def create
    @caja = Caja.new caja_params

    ir_a = @obra ? [@obra,@caja] : @caja

    respond_to do |format|
      if @caja.save
        format.html { redirect_to ir_a, notice: 'Caja creada con éxito.' }
        format.json { render action: 'show', status: :created, location: @caja }
      else
        # FIXME pasar situacion via controlador o helper
        params[:situacion] = @caja.situacion
        format.html { render action: 'new' }
        format.json { render json: @caja.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @caja.update(caja_params)
        format.html { redirect_to @caja, notice: 'Caja actualizada con éxito.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @caja.errors, status: :unprocessable_entity }
      end
    end
  end

  # las cajas solo se archivan cuando no tienen saldo
  def destroy
    if @caja.archivar
      respond_to do |format|
        format.html { redirect_to obra_cajas_url(@caja.obra) }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { render action: 'edit', location: @caja }
        format.json { render json: @caja.errors, status: :unprocessable_entity }
      end
    end
  end

  def cambiar
    @operacion = Operacion.new caja: @caja
  end

  def transferir
    @operacion = Operacion.new caja: @caja
  end

  def operar
    @operacion = Operacion.new operacion_params

    respond_to do |format|
      if @operacion.send(operacion)
        format.html { redirect_to obra_cajas_path(@caja.obra), notice: 'Operación realizada con éxito.' }
        format.json { head :no_content }
      else
        format.html { redirect_to obra_cajas_path(@caja.obra), notice: 'Ocurrió un error.' }
        format.json { render json: @operacion.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_caja
      @caja = (@obra.present? ? @obra.cajas : Caja).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caja_params
      params.require(:caja).permit(
        :obra_id, :situacion, :tipo, :banco, :numero
      )
    end

    # Operaciones permitidas
    def operaciones_validas
      %{ transferir cambiar }
    end

    # Devuelve la operación sólo si es válida
    def operacion
      if operaciones_validas.include?(params[:tipo_de_operacion])
        params[:tipo_de_operacion]
      else
        nil
      end
    end

    # Parámetros permitidos para las operaciones de caja
    def operacion_params
      params.require(:operacion).permit(
        :caja_id, :monto, :monto_moneda, :caja_destino_id,
        :monto_aceptado, :monto_aceptado_moneda
      )
    end
end

app/helpers/cajas_helper.rb
module CajasHelper

  def valor_situacion
    if @caja.new_record?
      params[:situacion]
    else
      @caja.situacion
    end
  end

  def opciones_formulario_caja
    case valor_situacion
      when 'banco'
        { form_caja: 'hidden',
          form_banco: '' }
      else
        { form_caja: '',
          form_banco: 'hidden' }
    end
  end

  def ver_en_caja
    @caja.efectivo? ? '' : 'hidden'
  end

  def ver_en_cuenta
    @caja.banco? ? '' : 'hidden'
  end

  def caja_o_cuenta(caja = @caja)
    if ( caja.efectivo? ) or ( params[:situacion] == 'efectivo' )
      'Caja'
    elsif ( caja.banco? ) or ( params[:situacion] == 'banco' )
      'Cuenta'
    else
      'Chequera'
    end
  end

  def ocultar_en_chequera
    caja_o_cuenta == 'Chequera' ? 'hidden' : ''
  end

  def obra_caja
    @caja.new_record? ? params[:obra_id] : @caja.obra_id
  end

  def establece_parametros_listado_cajas(situacion)
    case situacion
      when 'efectivo'
        lista_caja = ''
        lista_banco = 'hidden'
        ocultar_en_chequera = ''
      when 'banco'
        lista_caja = 'hidden'
        lista_banco = ''
        ocultar_en_chequera = ''
      when 'chequera'
        lista_caja = 'hidden'
        lista_banco = 'hidden'
        ocultar_en_chequera = 'hidden'
    end

    return [ lista_caja, lista_banco, ocultar_en_chequera ]
  end
end

app/views/cajas/_form.html.erb
<%# parametros ( form_banco )
    form_banco: oculta campos usados solo en el formulario de banco
    valor = [ 'hidden', '' ]
%>

<%= form_for @caja do |f| %>
  <%= f.error_messages %>
  <% if @caja.errors.any? %>
    <% @editar = true %>
  <% end %>

  <fieldset <%= editar_o_bloquear %>>

    <div class="row">

      <div class="field form-group col-md-2">
        <%= f.label :obra_id %>
        <%= f.collection_select(:obra_id, Obra.all, :id, :nombre, {
            prompt: '-Seleccione Obra-', selected: obra_caja }, { class: 'form-control' } ) %>
      </div>

      <div class="field form-group col-md-2 <%= form_banco %>">
        <%= f.label :banco %>
        <%= f.text_field :banco, class:'form-control' %>
      </div>

      <div class="field form-group col-md-2">
        <%= f.label :tipo %>
        <%= f.text_field :tipo, class:'form-control' %>
      </div>

      <div class="field form-group col-md-2 <%= form_banco %>">
        <%= f.label :numero %>
        <%= f.text_field :numero, class:'form-control' %>
      </div>

    </div>

  </fieldset>

  <%# campo necesario para crear un recibo nuevo %>
  <%= f.hidden_field :situacion, value: valor_situacion %>
  <%= hidden_field_tag :obra_id, obra_caja %>

  <br>

<% end %>

app/views/cajas/_list.html.erb
<%# TODO refactorizar %>
<% lista_caja = establece_parametros_listado_cajas(cajas.first.situacion)[0] %>
<% lista_banco = establece_parametros_listado_cajas(cajas.first.situacion)[1] %>
<% ocultar_en_chequera = establece_parametros_listado_cajas(cajas.first.situacion)[2] %>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th></th>
      <th>Obra</th>
      <th class="<%= lista_banco %>">Banco</th>
      <th>Tipo</th>
      <th class="<%= lista_banco %>">Numero</th>
      <th class="text-right">Saldo ARS</th>
      <th class="text-right <%= lista_caja %>">Saldo USD</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% cajas.each do |caja| %>
      <tr class="ir-a" data-uri="<%= con_obra? caja_path(caja.id)%>">
        <td><%= link_to '', @obra ? [ caja.obra, caja ] : caja, class: 'glyphicon glyphicon-eye-open' %></td>
        <td><%= caja.obra.nombre %></td>
        <td class="<%= lista_banco %>"><%= caja.banco %></td>
        <td><%= caja.tipo %></td>
        <td class="<%= lista_banco %>"><%= caja.numero %></td>
        <td class="text-right"><%= formatted_number(caja.total('ARS')) %> ARS</td>
        <td class="text-right <%= lista_caja %>"><%= formatted_number(caja.total('USD')) %> USD</td>
        <td class="text-center">
          <a class="btn btn-sm btn-info <%= lista_caja %>" href="<%= con_obra? cambiar_caja_path(caja) %>">
            Cambiar
          </a>
          <a type="button" class="btn btn-sm btn-info <%= ocultar_en_chequera %>" href="<%= con_obra? transferir_caja_path(caja) %>">
            Transferir
          </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cajas/_origen_de_operacion.html.erb
<div class="row origen">
  <%= f.hidden_field :caja_id %>

  <div class="field form-group col-md-1">
    <br>
    <label>Cambiar</label>
  </div>

  <div class="field form-group col-md-2">
    <%= render partial: 'layouts/selector_moneda', locals: {
          moneda: 'ARS', nombre: 'operacion[monto_moneda]' } %>
  </div>

  <div class="field form-group col-md-2">
    <label>Monto</label>
    <%= f.text_field :monto, class: 'form-control text-right monto',
        data: { role: 'money', a_sep: '.', a_dec: ',' } %>
  </div>
</div>

app/views/cajas/cambiar.html.erb
<div class="row">
  <h2>Cambio de Moneda</h2>
</div>

<%= form_for @operacion, url: operar_caja_path(@caja), method: :patch do |f| %>
  <%= hidden_field_tag :tipo_de_operacion, :cambiar %>

  <%= render partial: 'origen_de_operacion', locals: { f: f } %>

  <div class="row destino">
    <div class="field form-group col-md-1">
      <br>
      <label>Por</label>
    </div>

    <div class="field form-group col-md-2">
      <%= render partial: 'layouts/selector_moneda', locals: {
            moneda: 'ARS', nombre: 'operacion[monto_aceptado_moneda]' } %>
    </div>

    <div class="field form-group col-md-2">
      <label>Monto cambiado</label>
      <%= f.text_field :monto_aceptado, class: "form-control text-right monto",
          data: { role: 'money', a_sep: '.', a_dec: ',' } %>
    </div>

    <div class="field form-group col-md-2" >
      <br>
      <%= f.submit 'Operar', class: 'btn btn-success nivelar-boton form-control' %>
    </div>
  </div>
  <br>

<% end %>

app/views/cajas/cambio_moneda.html.erb
<div class="row">
  <h2>Cambio de Moneda</h2>
</div>

<%= render 'form_transfer', form_cambio: '',form_transfer: 'hidden'  %>

app/views/cajas/edit.html.erb
<h2>Editar <%= caja_o_cuenta %></h2>

<%= render 'form', opciones_formulario_caja %>

<a type="button" class="btn btn-danger col-md-2" href="<%= con_obra? caja_path %>" data-confirm="Estas seguro?" data-method="delete" rel="nofollow">
  <span class="glyphicon glyphicon-remove-circle"></span>
  Archivar <%= caja_o_cuenta %>
</a>
<a type="button" class="btn btn-warning col-md-2 col-md-offset-1" href="<%= con_obra? caja_path(@caja) %>">
  <span class="glyphicon glyphicon-eye-open"></span>
  Volver a <%= caja_o_cuenta %>
</a>
<a type="button" class="btn btn-success col-md-2 col-md-offset-1" id="btnGuardar">
  <span class="glyphicon glyphicon-ok"></span>
  Guardar Cambios
</a>

app/views/cajas/index.html.erb
<h2>Cajas
  <a type="button" class="btn btn-primary col-md-2 pull-right" href="<%= con_obra? new_caja_path(situacion: 'efectivo') %>">
    <span class="glyphicon glyphicon-plus"></span>
    Nueva Caja
  </a>
</h2>
<div id="cajas">
  <%= render 'list', cajas: @cajas %>
</div>
<br>

<h2>Cuentas
  <a type="button" class="btn btn-primary col-md-2 pull-right" href="<%= con_obra? new_caja_path(situacion: 'banco') %>">
    <span class="glyphicon glyphicon-plus"></span>
    Nueva Cuenta
  </a>
</h2>
<div id="cuentas">
  <%= render 'list', cajas: @cuentas %>
</div>
<br>

<h2>Chequeras</h2>
<div id="chequeras">
  <%= render 'list', cajas: @chequeras %>
</div>

app/views/cajas/new.html.erb
<h2>Nueva <%= caja_o_cuenta %></h2>

<%= render 'form' , opciones_formulario_caja %>

<div class="row">
  <a type="button" class="btn btn-warning col-md-2 col-md-offset-3" href="<%= con_obra? cajas_path %>">
    <span class="glyphicon glyphicon-eye-open"></span>
    Volver al Listado
  </a>
  <a type="button" class="btn btn-success col-md-2 col-md-offset-1" id="btnGuardar">
    <span class="glyphicon glyphicon-ok"></span>
    Guardar Cambios
  </a>
</div>

app/views/cajas/show.html.erb
<h2>Detalles de <%= caja_o_cuenta %></h2>

<%= render 'form', opciones_formulario_caja %>

<div class="row">
  <div class="col-md-2">
    <a type="button" class="btn btn-success col-md-12" href="<%= con_obra? cajas_path %>">
      <span class="glyphicon glyphicon-list-alt"></span>
      Listar <%= caja_o_cuenta.pluralize %>
    </a>
  </div>
  <div class="col-md-2 col-md-offset-1 <%= ocultar_en_chequera %>" >
    <a type="button" class="btn btn-warning col-md-12" href="<%= con_obra? edit_caja_path(@caja) %>">
      <span class="glyphicon glyphicon-edit"></span>
      Editar <%= caja_o_cuenta %>
    </a>
  </div>
</div>

<br>

<div class="row">
  <div class="field form-group col-md-2">
    <label>Saldo en ARS</label>
    <span class="form-control text-right"><%= formatted_number(@caja.total('ARS')) %></span>
  </div>
  <div class="field form-group col-md-2 col-md-offset-1 <%= ver_en_caja %>">
    <label>Saldo en USD</label>
    <span class="form-control text-right"><%= formatted_number(@caja.total('USD')) %></span>
  </div>
</div>

<% if @caja.chequera? %>
  <h4>Listado de Cheques</h4>
  <%= render 'cheques/list' %>
<% else %>
  <div class="row col-md-6">
    <h4>Listado de Movimientos</h4>
    <%= render 'movimientos/list', movimientos: @caja.movimientos %>
  </div>
<% end %>

app/views/cajas/transferencia.html.erb
<div class="row">
  <h2>Transferencia entre Cajas y Cuentas</h2>
</div>

<%= render 'form_transfer', form_cambio: 'hidden',form_transfer: ''  %>

app/views/cajas/transferir.html.erb
<div class="row">
  <h2>Transferencia desde <%= @caja.descripcion %></h2>
</div>

<%= form_for @operacion, url: operar_caja_path(@caja), method: :patch do |f| %>
  <%= hidden_field_tag :tipo_de_operacion, :transferir %>

  <%= render partial: 'origen_de_operacion', locals: { f: f } %>

  <div class="row destino">
    <div class="field form-group col-md-1">
      <br>
      <label>A</label>
    </div>

    <div class="field form-group col-md-4">
      <%# TODO se puede transferir de cuentas a cajas de efectivo y viceversa, o
          se hace con depósitos y extracciones independientes? %>
      <%= render partial: 'layouts/selector_cajas', locals: {
          cajas: @caja.obra.cajas.where.not(situacion: 'chequera').where.not(id: @caja.id),
          nombre: 'operacion[caja_destino_id]' } %>
    </div>

    <div class="field form-group col-md-2" >
      <br>
      <%= f.submit 'Operar', class: 'btn btn-success nivelar-boton form-control' %>
    </div>
  </div>
  <br>

<% end %>